### ISSUE TITLE
Part of Calyx org?

### ISSUE THREAD

**Issue by rachitnigam** [sgpthomas/tree-sitter-calyx#1]
Yo! This looks awesome (just stumbled across it). I've been meaning to do this for a bit but haven't had any time. If you would like, I think contributing it upstream into a calyxir/tree-sitter repo could be great.

You should have membership in that org but let me know if you don't!

**Comment by sgpthomas** [comment]
yeah id be happy to! I used it to write highlighting, jump to definition, and signatures of cells at point, and it was all pretty easy. super nice having an ast when writing editor integration

**Comment by sgpthomas** [comment]
looks like I don't have permission to create public repos

**Comment by rachitnigam** [comment]
Jump to definition was the big thing I also wanted to get when I was thinking about implementing this in tree-sitter to glad to hear it works!

**Comment by sgpthomas** [comment]
though makes me want to implement an LSP to do this in a editor generic fashion. and to make caching information easier

**Comment by rachitnigam** [comment]
Sent an invitation again! See if that works!

**Comment by sgpthomas** [comment]
cool that worked. migrated
